name: nf-core-rnafusion-1.0dev
channels:
  - bioconda
  - conda-forge
  - biocore
dependencies:
  - python=3.6
  - fastqc=0.11.7
  - multiqc=1.6
  - conda-forge::pandas=0.23.4
  - conda-forge::pyyaml=3.13
  - conda-forge::r-data.table=1.11.4
  - conda-forge::r-gplots=3.0.1
  - bioconductor-edger=3.20.7
  - conda-forge::r-markdown=0.8
