name: nf-core-rnafusion-arriba_1.2.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::arriba=1.2.0
  - bioconda::bioconductor-genomicalignments
  - bioconda::bioconductor-genomicranges
  - bioconda::samtools=1.9
  - bioconda::star=2.7.1a
  - conda-forge::openssl=1.0
  - conda-forge::r-circlize
  - conda-forge::readline=6.2