name: nf-core-rnafusion-star-fusion_1.8.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::dfam=2.0
  - bioconda::hmmer=3.2.1
  - bioconda::star-fusion=1.8.1
  - bioconda::jellyfish
  - bioconda::salmon=0.9.1
  - bioconda::trinity=2.8.5
