name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-tower:
    name: Run AWS full tests
    if: github.repository == 'nf-core/rnafusion'
    runs-on: ubuntu-latest
    steps:
      - name: Launch build workflow via tower
        uses: nf-core/tower-action@v3
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}",
              "genomes_base": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}/references",
              "build_references": "True"
            }
          nextflow_config: |
            process.errorStrategy = 'retry'
            process.maxRetries = 3
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_full_build,aws_tower \
          --all \
          --cosmic_username ${{ secrets.COSMIC_USERNAME }} --cosmic_passwd ${{ secrets.COSMIC_PASSWD }}
      - name: Launch workflow via tower
        uses: nf-core/tower-action@v3
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}"
            }
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_full,aws_tower \
          --all \
          --genomes_base /home/runner/work/rnafusion/rnafusion/results/references
