name: nf-core AWS test
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.
# It runs the -profile 'test' on AWS batch

on:
  workflow_dispatch:
jobs:
  run-tower:
    name: Run AWS tests
    if: github.repository == 'nf-core/rnafusion'
    runs-on: ubuntu-latest
    steps:
      # Launch workflow using Tower CLI tool action
      - name: Launch build arriba workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}",
              "genomes_base": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}/references",
              "cosmic_username": "${{ secrets.cosmic_username }}",
              "cosmic_passwd": "${{ secrets.cosmic_passwd }}",
              "arriba": true,
              "stub": true,
              "build_references": true
            }
          profiles: test,aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json

      - name: Launch arriba workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}",
              "genomes_base": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}/references",
              "cosmic_username": "${{ secrets.cosmic_username }}",
              "cosmic_passwd": "${{ secrets.cosmic_passwd }}",
              "arriba": true,
              "stub": true
            }
          profiles: test,aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json

      - name: Launch build starfusion workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}",
              "genomes_base": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}/references",
              "cosmic_username": "${{ secrets.cosmic_username }}",
              "cosmic_passwd": "${{ secrets.cosmic_passwd }}",
              "starfusion": true,
              "build_references": true,
              "stub": true
            }
          profiles: test,aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json

      - name: Launch starfusion workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}",
              "genomes_base": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}/references",
              "cosmic_username": "${{ secrets.cosmic_username }}",
              "cosmic_passwd": "${{ secrets.cosmic_passwd }}",
              "starfusion": true,
              "stub": true
            }
          profiles: test,aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json

      - name: Launch build fusioncatcher workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}",
              "genomes_base": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}/references",
              "cosmic_username": "${{ secrets.cosmic_username }}",
              "cosmic_passwd": "${{ secrets.cosmic_passwd }}",
              "fusioncatcher": true,
              "build_references": true,
              "stub": true
            }
          profiles: test,aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json

      - name: Launch fusioncatcher workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}",
              "genomes_base": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}/references",
              "cosmic_username": "${{ secrets.cosmic_username }}",
              "cosmic_passwd": "${{ secrets.cosmic_passwd }}",
              "fusioncatcher": true,
              "stub": true
            }
          profiles: test,aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json

      - name: Launch stringtie workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnafusion/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}",
              "genomes_base": "s3://${{ secrets.AWS_S3_BUCKET }}/rnafusion/results-${{ github.sha }}/references",
              "cosmic_username": "${{ secrets.cosmic_username }}",
              "cosmic_passwd": "${{ secrets.cosmic_passwd }}",
              "stringtie": true,
              "stub": true
            }
          profiles: test,aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json
